//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Task_List.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int User_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Due_Date { get; set; }
        public bool Task_Complete { get; set; }
        public int Task_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
